import { useState } from "react"
import { Card, FormField, Loader } from "../components"

const Home = () => {
  const [posts, setPosts] = useState(null)
  const [loading, setLoading] = useState(false)
  const [searchText, setSearchText] = useState("")

  return (
    <section className="mx-auto max-w-7xl">
      <div>
        <h1 className="text-[2rem] font-extrabold text-[#222328]">
          The Community Showcase
        </h1>
        <p className="mt-2 max-w-[500px] text-[1rem] text-[#666e75]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormField />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex items-center justify-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="mb-3 text-xl font-medium text-[#666e75]">
                Showing results for{" "}
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}
            <div className="xs:grid-cols-2 grid grid-cols-1 gap-3 sm:grid-cols-3 lg:grid-cols-4">
              {searchText ? (
                <RenderCards data={[]} title="No search results found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  )
}

const RenderCards = ({ data, title }) => {
  return data?.length > 0 ? (
    data.map((post) => <Card key={post._id} {...post} />)
  ) : (
    <h2 className="mt-5 text-xl font-bold uppercase text-[#6469ff]">{title}</h2>
  )
}

export default Home
